CREATE TABLE CRSS_data (
    KEY VARCHAR PRIMARY KEY,
    BODY_TYP INT NOT NULL,
    SPEEDREL INT NOT NULL,
    AGE FLOAT NOT NULL,
    SEX FLOAT NOT NULL,
    DRUGS FLOAT NOT NULL,
    INJ_SEV INT NOT NULL,
    MAN_COLL INT NOT NULL,
    WEATHER INT NOT NULL,
    MONTH INT NOT NULL,
    HOUR INT NOT NULL,
    DAY_WEEK INT NOT NULL,
    ALCOHOL INT NOT NULL
); 